name: Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x]

    steps:
      - name: Checkout the application
        uses: actions/checkout@v2
      - name: Get yarn cache directory
        id: cache-yarn-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-yarn-dir.outputs.dir }}
          key: ${{ runner.os }}-modeules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules- 
            ${{ runner.os }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check lint
        run: yarn lint
      - name: Build the project
        run: yarn build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.PORTFOLIO_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.API_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN","NETLIFY_SITE_ID"]'
